version: '3.8'

services:
  onfuture:
    container_name: onfuture-web
    restart: unless-stopped
    build:
      context: https://github.com/aliyabuz25/onfuture-web-2.git
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=6985
    volumes:
      - /datastore/onfuture/logs.json:/app/logs.json
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.onfuture.rule=Host(`onfuture.az`) || Host(`www.onfuture.az`)'
      - 'traefik.http.routers.onfuture.entrypoints=web'
      - 'traefik.http.services.onfuture.loadbalancer.server.port=6985'
      - 'com.centurylinklabs.watchtower.enable=true'

networks:
  edge:
    external: true
